### ISSUE TITLE
Bug with MythicMobs v5.0.0 alpha1

### ISSUE THREAD

**Issue by Narfman24** [SXRWahrheit/MythicMobs-Files#2]
https://pastebin.com/71gYKNzc

Please help, every mobs spawn as PIG

**Comment by SXRWahrheit** [comment]
These files are provided as-is, with no warranty whatsoever. They are provided for learning purposes. This repo does not exist for technical support, and I can confirm that they work fine on my live server.

If you are using my files on my server, you must:
1) Provide credit to me in-game for creating them
2) Not accept any donations or payments of any kind (i.e. maintain a non-commercial server)

Help using MythicMobs is available only through the MythicMobs community, not this repository.
